### ISSUE TITLE
Workspace on mobile

### ISSUE THREAD

**Issue by fringy138** [cncjs/cncjs#153]
I am unable to view/use the web interface on mobile since updating to v1.9.1. It works fine on my computer, but on mobile I see "loading" for a second then only a black screen. 

Is anyone else having this problem?

**Comment by AustinSaintAubin** [comment]
I have noticed this as well.

**Comment by cheton** [comment]
Fixed in commit bf9f67f62cb71230ac5cd70be52a7db29baf2587

Also found several layout issues with mobile view, I'll look at it in the following days.

**Comment by yfilali** [comment]
Would it be possible to have a small bug release for this mobile fix? the latest on npm doesn't have the fix above.

**Comment by cheton** [comment]
Sorry for the delay. I just got back from a 7 day trip to Okinawa.

I will publish a new release today to resolve the blank screen issue on mobile. However, the mobile layout problem is not easy to resolve, I will try to fix it in a future release.

**Comment by cheton** [comment]
The blank screen issue was fixed in v1.9.2.

Note that in this version, it didn't completely fix the UI layout problem on mobile devices, you may have to use an iPhone 6 Plus or a larger iPad display in the landscape mode, or you will encounter problems while scrolling.

![file 17-04-2017 7 10 09 pm](https://cloud.githubusercontent.com/assets/447801/25087456/a0ee3ae2-23a1-11e7-84b6-05f6cba03dbf.png)

**Comment by yfilali** [comment]
Sorry, forgot to reply. Yes, I tested this and it at least works very nicely on iPad now. Thank you very much!
