### ISSUE TITLE
Desktop app for Raspberry Pi

### ISSUE THREAD

**Issue by yasamoka** [cncjs/cncjs#284]
Hello,

Would it be possible to provide a desktop app built for ARMv6/7 that runs on the Raspberry Pi?

I am currently running CNC.js locally on the Raspberry Pi. Other machines have access via the web interface. However, Chromium, despite being the version optimized for the Raspberry Pi, is somewhat slow and not very responsive, even on a Raspberry Pi 3. A desktop app, I presume, would take care of that instantly.

Thank you very much for your awesome software.

**Comment by MitchBradley** [comment]
The way that CNCjs desktop apps work is that the browser and the CNCjs code are bundled together into a single executable - so any deficiencies of Chromium on a given platform affect the app too.

**Comment by cheton** [comment]
Hi @yasamoka,

It's not recommended to run the desktop app on a Raspberry Pi, it will consume a large amount of CPU and memory resources for rendering the normal UI, especially the 3D view.

My suggestion: If you want to access the web interface via Chromium on a Raspberry Pi, you can use a simplified CNCjs UI especially designed for tablet (https://github.com/cncjs/cncjs-shopfloor-tablet), it only needs a small amount of recoures than the normal UI since it does not use 3D graphics.

**Comment by yasamoka** [comment]
I see. Thank you very much. I will try the suggested UI.
