### ISSUE TITLE
Many unnecessary things in the UI

### ISSUE THREAD

**Issue by makarenya** [cncjs/cncjs#383]
#### Description

Hi!
I'm using cncjs, and i found, that it sometimes have a LOT of unnecessary UI items. My CNC have Marlin firmware (yes, it is 3 in 1 homemade device), and, for example, it hasn't any work coordinates system. Really, Marlin have only ONE coordinate system, that can be switched to zero in any point. And Marlin have no coolant Control, but i have coolant buttons... And many many more unused things.

In the same time, the Primary things, that I need to:
- Home all axis (Z first, and then X and Y simultaneously)
- Zero XY plane at current point
- Zero Z axis at current point
This is features, that i need every time, that i use CNC - and I can get it only through second level of menu. (XY simultaneously homing not available at all)...
As result - many things, that don't working on my firmware - I see it all behind my face, and few things, that i really need - i cat reach only from deep menus...

#### Versions

- CNCjs: 1.9.x
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?
NPM

#### CNC Controller

Marlin

#### Hardware

Raspberry Pi

#### Operating System

Not Applicable

**Comment by MitchBradley** [comment]
You might consider one of the simplified UIs like cncjs-shopfloor-tablet .  I wrote it to do exactly what I need with no extra clutter, which sounds like what you are asking for.  Some modifications would be needed to do exactly what you want, but it is easier to modify than the full-blown cncjs because the code is much smaller with fewer dependencies on huge frameworks.

**Comment by cheton** [comment]
Hi @makarenya 

You can create MDI buttons to fulfill your needs. It's available since v1.9.13.

![](https://user-images.githubusercontent.com/447801/35484169-4137892e-0487-11e8-8077-935c30db0321.png)

Toggle MDI mode
![](https://user-images.githubusercontent.com/447801/35484157-05d67dfe-0487-11e8-8d12-1d519611d075.png)
