### ISSUE TITLE
TinyG: restart during a file run?

### ISSUE THREAD

**Issue by phillips82** [cncjs/cncjs#404]
#### Description

During a large 100,000+ line file at times I will encounter an error, not a CNCJS error. Causing me to need to restart the file. Currently, that I know, I can only restart from the beginning of a file. This wastes hours sometimes. Is there a setting to restart at a certain line in a file? Allowing you to not start at the beginning of a file?

#### Versions

- CNCjs: 1.9.10 & 1.9.15

#### How Do You Install CNCjs?

- [x] Download the CNCjs Desktop Application

#### CNC Controller

- [x] TinyG/g2core

#### Hardware

- [x] Desktop

#### Operating System

- [x] Windows

**Comment by MitchBradley** [comment]
CNCjs has no such feature.  Restarting GCode is very tricky in general, due to the controller's need to consider multiple lines at once in order to make smooth moves at corners.  Error reports are typically not precisely synchronized with machine motion due to such "planner queuing" and other "look ahead" factors.  As an analogy, consider the difficulty of restarting an auto race after an accident has occurred.  You cannot just "freeze everything instantaneously and then start from that state later". 

You could make a copy of the file and edit out the initial lines that you want to skip, being careful to add code at the beginning to establish any modes that were in effect when the error happened, and setting the tool position and spindle states appropriately.   It can make it tricky to know just where to start the tool since the stopping point might not be exactly at a GCode line boundary (because of the multi-line planning cited above).   One possible mitigation would be to keep a few lines before the error, making "air cuts" for those lines.
