### ISSUE TITLE
Feature Request: Check build size, run out to each corner of work area

### ISSUE THREAD

**Issue by djdemer** [cncjs/cncjs#455]
#### Description

It would be nice simple feature to have after zeroing and loading the gcode, you could request the spindle to move to each x,y corner of the work area to aid in visually placing and securing the work piece.  This allows you to check the intended work area extremes to center your work and check clearances of all hold downs before committing to Running of the gcode. 

#### Versions
- CNCjs: 1.9.x

#### How Do You Install CNCjs?
- [x] NPM

#### CNC Controller
- [x] Grbl

#### Hardware
- [x] Raspberry Pi
- [x ] Desktop or Laptop

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by cheton** [comment]
@djdemer 

You can create a macro to perform perimeter tracing using bounding box variables: `xmin`, `xmax`, `ymin`, `ymax`, `zmin`, `zmax`. Those variables will be set after loading a G-code program.

https://github.com/cncjs/cncjs/wiki/User-Guide#examples
#### Traverse around the boundary
```gcode
G90
G0 Z10 ; go to z-safe
G0 X[xmin] Y[ymin]
G0 X[xmax]
G0 Y[ymax]
G0 X[xmin]
G0 Y[ymin]
```

**Comment by cheton** [comment]
![image](https://user-images.githubusercontent.com/447801/56187506-608f4700-6055-11e9-8509-a3f1f28481bd.png)

**Comment by djdemer** [comment]
Very Much appreciated for the quick response!  Thank you.

**Comment by einencool** [comment]
Hello, 
I'm new to CNCjs. 
is there also the possibility to check the outside of a cylinder? What would the G-Code look like for something like this? 
is it possible to move to the center of the G-Code and after that to the bottom left corner. I'm asking, because I'm using a laser, and this would make things definitively easier.

Is something like this possible? (It's the Code from Lasergrbl I'm using for the diameter)
G00 X[xmin] Y[ymax/2-ymin/2+ymin] F5000
M4 S1
F1000 
G02 Y[ymax/2-ymin/2+ymin] I[ymax/2-ymin/2]
M5 S0
G00 X0 Y0 F5000

My Raspberry Pi is on the way, so I can't test it in the moment, but maybe you know how the code has to be.

Greets in Advance
Chris

**Comment by dlarue** [comment]
Works GREAT!  I just had to turn off the Z move, turn on the laser, do the move and turn the laser off.
Thank you.
G90
G1F2000
M3S10; turn on the spindle/laser
;G0 Z10 ; go to z-safe
G1 X[xmin] Y[ymin]
G1 X[xmax]
G1 Y[ymax]
G1 X[xmin]
G1 Y[ymin]
M5S0
;$H

**Comment by dlarue** [comment]
Now I just need to figure out how to Run the macro in one mouse click as opposed to clicking the Run Macro button on the macro list and having to move to the RUN button on the macro dialog box which popped up instead of running it.  

alignment can be a tricky thing so most using Lightburn will hold the shift key down and hit the fame button which can be repeated without moving the mouse cursor so one hand on the keyboard and the other adjusting the material.
