### ISSUE TITLE
$G command spamming in desktop app - V1.10.1 

### ISSUE THREAD

**Issue by FlyerLife22** [cncjs/cncjs#805]
#### Description

the desktop app keeps sending $G command when connected to FluidNC.  

#### Versions

- CNCjs: 1.10.1

#### How Do You Install CNCjs?

- [x ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl (FluidNC)
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [] Raspberry Pi
- [x] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [] Not Applicable
- [ x ] Windows
- [ ] Mac
- [ ] Linux

![image](https://user-images.githubusercontent.com/117743635/215271730-2df161cc-9fef-4707-b89b-10bce2224e60.png)

**Comment by MitchBradley** [comment]
CNCjs has always done that, but usually you do not see the results in the console because CNCjs hides it.  The problem is a bug in one particular version of FluidNC - the "T" in the result is missing a number following it.  That bug has been fixed and the fix will appear in the next FluidNC release.
